[package]
name = "async-ringbuffer"
version = "0.2.0"
authors = ["AljoschaMeyer <mail@aljoscha-meyer.de>"]
description = "A nonblocking spsc ring buffer with fixed capacity."
readme = "README.md"
license = "GPL-3.0"
repository = "https://github.com/AljoschaMeyer/async-ringbuffer"

[dependencies]
tokio-io = "0.1.2"
futures = "0.1.17"

[dev-dependencies]
quickcheck = "0.4.1"
void = "1.0.2"
rand = "0.3.18"
