[package]
name = "async-ringbuffer"
version = "0.3.0"
authors = ["AljoschaMeyer <mail@aljoscha-meyer.de>"]
description = "A nonblocking spsc ring buffer with fixed capacity."
readme = "README.md"
license = "AGPL-3.0"
repository = "https://github.com/AljoschaMeyer/async-ringbuffer"

[dependencies]
futures-core = "0.2.0-beta"
futures-io = "0.2.0-beta"

[dev-dependencies]
futures = "0.2.0-beta"
